#!/bin/bash

function gstat(){

  wdir="/home/adrian/bin/gits"
  declare -a commit; commit=("")
  declare -a total; total=("")
  local lines; lines=$(git status -bs | wc -l)
  local llwd; llwd=$(pwd)
  local lastdir; lastdir=$(ls $wdir | sort -r | awk 'NR==1 {print $0}')
  if [[ "$lines" -eq 1 ]]; then
    total+=("$(pwd)")
  else
    commit+=("$(pwd)")
  fi
  git status -bs
  if [[ "${total[-1]}" = "${llwd:22}" ]]; then #TODO condition
    for i in "${commit[@]}"
    do
      echo ${i:22}
    done
  fi
}


function main(){
  local cdir; cdir=$(pwd)
  local wdir; wdir="/home/adrian/bin/gits"
  local tmpfile; tmpfile="/tmp/gitstatus.file"
  local mdate; mdate=$(date +'%Y-%m-%d-%T')

  cd "$wdir"
  gits="$(ls "$(pwd)")"
  clear
  printf '\e[31;5m%s\033[0m\n\e[21m%s\033[0m\n\e[36m%s\033[0m\n\n' "!GIT!" "$mdate" "Status overview of local git repositories from $wdir"

  find . -maxdepth 2 -mindepth 1 -type d -printf '%f\n'
#  for i in $gits
#  do
#    cd "$i"
#    if [[ ! -d ".git" ]]; then
#      printf '\t\t%s\n' "No git repo in ${i^^}"
#      continue
#    fi
#    gstat
#  done

  cd "$cdir"
  exit 0
}
main "$@"

